# Generated by Django 3.2 on 2021-04-07 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('ph_value', models.FloatField(null=True)),
                ('moisture', models.FloatField(null=True)),
                ('crop', models.CharField(max_length=256, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CropsHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
