# Generated by Django 3.2 on 2021-04-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPKValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(null=True)),
                ('p', models.FloatField(null=True)),
                ('k', models.FloatField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NPKValues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
