# Generated by Django 3.2 on 2021-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_npkvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='npkvalues',
            name='deviceId',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
