# Generated by Django 3.2 on 2021-04-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_npkvalues_deviceid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NPKValues',
        ),
    ]
