# Generated by Django 3.2 on 2021-04-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_delete_npkvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropshistory',
            name='k',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cropshistory',
            name='n',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cropshistory',
            name='p',
            field=models.FloatField(null=True),
        ),
    ]
